### ISSUE TITLE
MCU Crash (MCU 'mcu' shutdown: Timer too close) when VGB is activated

### ISSUE THREAD

**Issue by milkam** [Deutherius/VGB#1]
I do not even finish the first layer of a print. 
I think as soon as it's trying to update the bed mesh it crash. 
At first I did with .1 degrees increment. It was crashing very early in the print. 
then I did with .2 increment. It was crashing later in the first layer..

Forget to specify. The macro does set the bed mesh when it's not printing without any issue.. It's while it's printing the issue occurs. 

Kliper version 10.0.122

I think I need to specify, that as Soon as I disable the VGB macro.. I can print again.. 
I think the idea of this is great.. Like really a life saver great style.. But sadly It make the printer MCU crash :(

**Comment by Deutherius** [comment]
Sounds to me like your mcu can't handle loading a new mesh mid-print (since the main macro should run every ~10 seconds). What Pi are you using? Can you try loading a different mesh mid-print manually (can be a dry run without filament, no need to waste any).

**Comment by milkam** [comment]
Hi Deutherius, Thanks for answering. Sure I can try
The MCU is an BTT Octopus which should have a Powerful enough MCU. 
The PI is a 3b+
I started a small print.. Since it would not waste soo much filament. 
And I was able to change bed mesh every 1-2 seconds without causing any issues. 
![image](https://user-images.githubusercontent.com/6866885/143776295-fceb9f79-12e6-4a02-84a5-ba98f59624a2.png)
So I would suppose it's something in the macro.. 
First Time I really look at such a macro.. I'm a Java Developper and I don't understand much of it.. Lol. So many Variable here and there. :P 
But if I can help I will be more than happy to do anything you ask me.. I would really like this to work. 

As soon as my current print finish though 40min. I'll update klipper to the latest version...  
I'm at klipper 0-122,  will go to 0-167
And then will try again vgb

**Comment by Deutherius** [comment]
We worked this out over discord - if you forget to set up the generated mesh constants (min temp, max temp and step size), the algorithm will work with the stock values (which are intentionally ridiculously extreme) - this will cause a lot of code to be executed, potentially taxing the Pi too much. I will be implementing a safeguard against this shortly.
