### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by Metti93** [Deutherius/VGB#11]
i can't get the script running, i got the same error every time

```
pi@mainsailos:~/printer_data/config $ python3 generate_VGB_meshes.py printer.cfg 0.2 7
Traceback (most recent call last):
  File "/home/pi/printer_data/config/generate_VGB_meshes.py", line 56, in <module>
    postamble.pop()
IndexError: pop from empty list
```

<img width="649" alt="Bildschirmfoto 2023-09-22 um 21 11 23" src="https://github.com/Deutherius/VGB/assets/48029820/cf1cc455-fb8a-4efc-940b-aa93be314fef">

**Comment by Deutherius** [comment]
Please include the printer.cfg file you are trying to run the script on

**Comment by Metti93** [comment]
[printer.txt](https://github.com/Deutherius/VGB/files/12704333/printer.txt)

**Comment by Deutherius** [comment]
Should be fixed, please retry with new script
