### ISSUE TITLE
long decimal bed meshes

### ISSUE THREAD

**Issue by MakManIfest** [Deutherius/VGB#4]
After generating the meshes and new printer.cfg, the vgb macro keeps requesting meshes that don't exist. For example:

bed_mesh: Unknown profile [38.400000000000006]
bed_mesh: Unknown profile [38.50000000000001]

The script did generate weird bed meshes with large decimals on some temperatures but not on others???

There are bed meshes 38.5 and 38.4. why is it requesting the bed meshes with all the decimals? Why is it even generating bed meshes with more than 1 decimal?

**Comment by Deutherius** [comment]
Can you include your specific VGB.cfg and the printer.cfg that you generated the meshes from?

**Comment by MakManIfest** [comment]
No problem.
[VGB.zip](https://github.com/Deutherius/VGB/files/9543369/VGB.zip)

**Comment by Deutherius** [comment]
Replicated the issue, should now be fixed, please try again with the updated script

**Comment by MakManIfest** [comment]
Wow, very fast. Thank you.
I will test after work.

**Comment by MakManIfest** [comment]
Issue fixed! Thank you again!
