### ISSUE TITLE
Bed mesh parameters different from COLD and HOT mesh

### ISSUE THREAD

**Issue by barbarioli1** [Deutherius/VGB#5]
The error happened because I had a default bed mesh with 5x5 mesh points and  40mm for min value  and 260 for max value. However the COLD and HOT meshes had 9x9 bedmesh, 20mm min value and 280mm max value.
Below you can see one of the wrong generated codes:

> #*# [bed_mesh 39.1]
> #*# version = 1
> #*# points =
> #*# 	0.047518, 0.072811, 0.049122, 0.078049, 0.057159, 0.064183, 0.071506, 0.074604, 0.068293
> #*# 	0.036256, 0.082037, 0.056024, 0.074299, 0.069713, 0.048226, 0.041439, 0.049354, 0.049652
> #*# 	0.031372, 0.023159, 0.023396, 0.039470, 0.067567, 0.022921, 0.027982, 0.040659, 0.018098
> #*# 	-0.020354, 0.001488, -0.002854, 0.007024, 0.002561, -0.021250, -0.009939, -0.013390, -0.028573
> #*# 	-0.045774, -0.016250, -0.011488, 0.012561, 0.000000, -0.025000, -0.004762, -0.016848, -0.026073
> #*# 	-0.026012, -0.009939, -0.011726, -0.002854, 0.014878, -0.002677, -0.011488, -0.030713, -0.019287
> #*# 	0.005720, 0.022982, 0.034829, 0.027506, 0.036134, 0.028634, 0.032445, 0.012146, 0.004171
> #*# 	0.000604, 0.048640, 0.025189, 0.044415, 0.059177, 0.053402, 0.049652, 0.050488, 0.031378
> #*# 	0.034067, 0.058470, 0.046506, 0.068232, 0.069720, 0.051683, 0.071567, 0.061030, 0.043945
> #*# tension = 0.2
> #*# min_x = 40.0
> #*# algo = bicubic
> #*# y_count = 5
> #*# mesh_y_pps = 2
> #*# min_y = 40.0
> #*# x_count = 5
> #*# max_y = 260.0
> #*# mesh_x_pps = 2
> #*# max_x = 260.0

And the expected code would be:

> #*# [bed_mesh 39.1]
> #*# version = 1
> #*# points =
> #*# 	0.047518, 0.072811, 0.049122, 0.078049, 0.057159, 0.064183, 0.071506, 0.074604, 0.068293
> #*# 	0.036256, 0.082037, 0.056024, 0.074299, 0.069713, 0.048226, 0.041439, 0.049354, 0.049652
> #*# 	0.031372, 0.023159, 0.023396, 0.039470, 0.067567, 0.022921, 0.027982, 0.040659, 0.018098
> #*# 	-0.020354, 0.001488, -0.002854, 0.007024, 0.002561, -0.021250, -0.009939, -0.013390, -0.028573
> #*# 	-0.045774, -0.016250, -0.011488, 0.012561, 0.000000, -0.025000, -0.004762, -0.016848, -0.026073
> #*# 	-0.026012, -0.009939, -0.011726, -0.002854, 0.014878, -0.002677, -0.011488, -0.030713, -0.019287
> #*# 	0.005720, 0.022982, 0.034829, 0.027506, 0.036134, 0.028634, 0.032445, 0.012146, 0.004171
> #*# 	0.000604, 0.048640, 0.025189, 0.044415, 0.059177, 0.053402, 0.049652, 0.050488, 0.031378
> #*# 	0.034067, 0.058470, 0.046506, 0.068232, 0.069720, 0.051683, 0.071567, 0.061030, 0.043945
> #*# tension = 0.2
> #*# mesh_x_pps = 2
> #*# algo = bicubic
> #*# min_x = 20.0
> #*# min_y = 20.0
> #*# y_count = 9
> #*# mesh_y_pps = 2
> #*# x_count = 9
> #*# max_x = 280.0
> #*# max_y = 280.0

I'm out of free time to tackle this right now, but you may want to warn the user that all the meshes kept on the printer,cfg must have the same configuration (grid size, algorithm, min and max values), in order for the python script to work.

Thank you for the effort that you have put on this!

**Comment by Deutherius** [comment]
> I'm out of free time to tackle this right now

That makes two of us :D Thanks for the suggestion, added.
