### ISSUE TITLE
Klipper change to bed mesh loading....any impact on VGB?

### ISSUE THREAD

**Issue by PhilBaz** [Deutherius/VGB#7]
Any impact for VGB users? I imagine not?
![nbvnbv](https://user-images.githubusercontent.com/21558241/212483648-c3540c0a-431d-4680-83c0-ba949637ff19.jpg)

**Comment by Deutherius** [comment]
There should be no impact to VGB from this, as VGB loads its own meshes anyway. There will just be a brief period (couple seconds) on printer start where isntead of the default bed mesh, no bed mesh will be loaded.

**Comment by PhilBaz** [comment]
@Deutherius Cool.
